/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sms_desktop;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hanafi
 */
public final class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    Koneksi koneksi = new Koneksi();
    DefaultTableModel model1;
    DefaultTableModel model2;
    String[][] isimasuk;
    String[][] isikeluar;
    String CurentUser = null;
    DefaultComboBoxModel combomodel;

    public Dashboard() {
        initComponents();
        koneksi.koneksi();
        LoginForm.setVisible(true);
        autorefresh();
        isiKotakKeluar();
    }

    void autorefresh() {
        Thread runing1 = new Thread() {
            @Override
            public void run() {
                int saat_ini = 0;
                while (true) {
                    int cek = koneksi.getId(saat_ini, CurentUser);
                    if (cek != saat_ini) {
                        isiKotakMasuk();
                        saat_ini = cek;
                    }
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                    }
                }
            }
        };
        runing1.start();
        Thread runing2 = new Thread() {
            @Override
            public void run() {
                int saat_ini = 0;
                while (true) {
                    int cek = koneksi.getCountUser(saat_ini);
                    if (cek != saat_ini) {
                        isiReciver();
                        saat_ini = cek;
                    }
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                    }
                }
            }
        };
        runing2.start();
    }

    void isiReciver() {
        ArrayList<String> listUser = koneksi.getUsers();
        String[] userarray = new String[listUser.size()];
        int x = 0;
        for (String u : listUser) {
            userarray[x] = u;
            x++;
        }
        combomodel = new DefaultComboBoxModel(userarray);
        target.setModel(combomodel);
    }

    void isiKotakMasuk() {
        ResultSet rs = koneksi.aksesData("Pesan", "Count,Pengirim,IsiPesan", "Penerima", CurentUser);
        isimasuk = new String[100][3];
        try {
            int c = 0;
            while (rs.next()) {
                isimasuk[c][0] = rs.getString("Pengirim");
                isimasuk[c][1] = rs.getString("IsiPesan");
                isimasuk[c][2] = rs.getString("Count");
                c++;
            }
        } catch (SQLException ex) {
        }
        String[] head = {"Pengirim", "Pesan"};
        model1 = new DefaultTableModel(isimasuk, head);
        TBMasuk.setModel(model1);
    }

    void isiKotakKeluar() {
        ResultSet rs = koneksi.aksesData("Pesan", "Count,Penerima,IsiPesan", "Pengirim", CurentUser);
        isikeluar = new String[100][3];
        try {
            int c = 0;
            while (rs.next()) {
                isikeluar[c][0] = rs.getString("Penerima");
                isikeluar[c][1] = rs.getString("IsiPesan");
                isikeluar[c][2] = rs.getString("Count");
                c++;
            }
        } catch (SQLException ex) {
        }
        String[] head = {"Penerima", "Pesan"};
        model2 = new DefaultTableModel(isikeluar, head);
        TBKeluar.setModel(model2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginForm = new javax.swing.JDialog();
        username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        SendForm = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        isitext = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        target = new javax.swing.JComboBox<>();
        DaftarForm = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        daftar_nama = new javax.swing.JTextField();
        daftar_pass = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Background = new javax.swing.JPanel();
        TabPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBMasuk = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        isi1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBKeluar = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        isi2 = new javax.swing.JTextArea();
        Userini = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        LoginForm.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        LoginForm.setTitle("LOGIN");
        LoginForm.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        LoginForm.setLocation(new java.awt.Point(480, 250));
        LoginForm.setMinimumSize(new java.awt.Dimension(382, 135));
        LoginForm.setModal(true);
        LoginForm.setPreferredSize(new java.awt.Dimension(382, 135));
        LoginForm.setResizable(false);
        LoginForm.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                LoginFormWindowClosing(evt);
            }
        });

        jLabel2.setText("Nama");

        jLabel3.setText("Password");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Daftar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginFormLayout = new javax.swing.GroupLayout(LoginForm.getContentPane());
        LoginForm.getContentPane().setLayout(LoginFormLayout);
        LoginFormLayout.setHorizontalGroup(
            LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginFormLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginFormLayout.createSequentialGroup()
                        .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(password))))
                .addContainerGap())
        );
        LoginFormLayout.setVerticalGroup(
            LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        SendForm.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        SendForm.setLocation(new java.awt.Point(420, 210));
        SendForm.setMinimumSize(new java.awt.Dimension(422, 295));
        SendForm.setModal(true);
        SendForm.setResizable(false);
        SendForm.setSize(new java.awt.Dimension(422, 295));

        isitext.setColumns(20);
        isitext.setLineWrap(true);
        isitext.setRows(5);
        isitext.setWrapStyleWord(true);
        jScrollPane5.setViewportView(isitext);

        jButton2.setText("Send");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Send To :");

        javax.swing.GroupLayout SendFormLayout = new javax.swing.GroupLayout(SendForm.getContentPane());
        SendForm.getContentPane().setLayout(SendFormLayout);
        SendFormLayout.setHorizontalGroup(
            SendFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
            .addGroup(SendFormLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2))
            .addGroup(SendFormLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(target, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SendFormLayout.setVerticalGroup(
            SendFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SendFormLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(SendFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(target, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DaftarForm.setTitle("Daftar");
        DaftarForm.setLocation(new java.awt.Point(430, 200));
        DaftarForm.setModal(true);
        DaftarForm.setResizable(false);
        DaftarForm.setSize(new java.awt.Dimension(413, 418));

        jLabel1.setText("Nama");

        jLabel5.setText("Password");

        jButton4.setText("Daftar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Batalkan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DaftarFormLayout = new javax.swing.GroupLayout(DaftarForm.getContentPane());
        DaftarForm.getContentPane().setLayout(DaftarFormLayout);
        DaftarFormLayout.setHorizontalGroup(
            DaftarFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DaftarFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DaftarFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DaftarFormLayout.createSequentialGroup()
                        .addGap(0, 207, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(DaftarFormLayout.createSequentialGroup()
                        .addGroup(DaftarFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(DaftarFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(daftar_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(daftar_nama))))
                .addContainerGap())
        );
        DaftarFormLayout.setVerticalGroup(
            DaftarFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DaftarFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DaftarFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(daftar_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DaftarFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(daftar_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 325, Short.MAX_VALUE)
                .addGroup(DaftarFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        TBMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TBMasuk.setRowHeight(20);
        TBMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TBMasukMousePressed(evt);
            }
        });
        TBMasuk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TBMasukKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TBMasuk);

        isi1.setEditable(false);
        isi1.setColumns(20);
        isi1.setLineWrap(true);
        isi1.setRows(5);
        isi1.setWrapStyleWord(true);
        jScrollPane4.setViewportView(isi1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
            .addComponent(jScrollPane4)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
        );

        TabPane.addTab("Kotak Masuk", null, jPanel1, "");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        TBKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TBKeluar.setRowHeight(20);
        TBKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TBKeluarMousePressed(evt);
            }
        });
        TBKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TBKeluarKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(TBKeluar);

        isi2.setEditable(false);
        isi2.setColumns(20);
        isi2.setLineWrap(true);
        isi2.setRows(5);
        isi2.setWrapStyleWord(true);
        jScrollPane3.setViewportView(isi2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
        );

        TabPane.addTab("Kotak Keluar", jPanel2);

        Userini.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabPane)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Userini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addComponent(Userini, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(Background, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Pesan");

        jMenuItem1.setText("Pesan Baru");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Hapus Semua Pesan Dierima");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Hapus Semua Pesan Terkirim");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TBMasukMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBMasukMousePressed
        // TODO add your handling code here:
        if (TBMasuk.getValueAt(TBMasuk.getSelectedRow(), 1) != null) {
            isi1.setText("" + TBMasuk.getValueAt(TBMasuk.getSelectedRow(), 1));
        } else {
            isi1.setText("");
        }
    }//GEN-LAST:event_TBMasukMousePressed

    private void TBKeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBKeluarMousePressed
        // TODO add your handling code here:
        if (TBKeluar.getValueAt(TBKeluar.getSelectedRow(), 1) != null) {
            isi2.setText("" + TBKeluar.getValueAt(TBKeluar.getSelectedRow(), 1));
        } else {
            isi2.setText("");
        }
    }//GEN-LAST:event_TBKeluarMousePressed

    private void LoginFormWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_LoginFormWindowClosing
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LoginFormWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CurentUser = koneksi.getUser(username.getText(), password.getText());
        System.out.println(CurentUser);
        if (CurentUser != null) {
            Userini.setText("Login as "+CurentUser);
            LoginForm.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "User dan Password Tidak Valid");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        SendForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String tanggal = " \n\n\n\n => Waktu Kirim \n" + (new Date());
        koneksi.sending(CurentUser, target.getSelectedItem().toString(), isitext.getText() + tanggal);
        isitext.setText("");
        isiKotakKeluar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DaftarForm.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DaftarForm.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        koneksi.register(daftar_nama.getText(), daftar_pass.getText());
        DaftarForm.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void TBMasukKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TBMasukKeyReleased
        // TODO add your handling code here:
        if (TBMasuk.getValueAt(TBMasuk.getSelectedRow(), 1) != null) {
            isi1.setText("" + TBMasuk.getValueAt(TBMasuk.getSelectedRow(), 1));
        } else {
            isi1.setText("");
        }
    }//GEN-LAST:event_TBMasukKeyReleased

    private void TBKeluarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TBKeluarKeyReleased
        // TODO add your handling code here:
        if (TBKeluar.getValueAt(TBKeluar.getSelectedRow(), 1) != null) {
            isi2.setText("" + TBKeluar.getValueAt(TBKeluar.getSelectedRow(), 1));
        } else {
            isi2.setText("");
        }
    }//GEN-LAST:event_TBKeluarKeyReleased

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        int i=JOptionPane.showConfirmDialog(this, "Semua pesan inbox User ini akan dihapus termasuk pesan pada outbox user lain"
                + "\nApakaah Anda yakin?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (i==JOptionPane.YES_OPTION){
            koneksi.delete("Pesan", "Penerima", CurentUser);
            isiKotakKeluar();
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        int i=JOptionPane.showConfirmDialog(this, "Semua pesan oubox User ini akan dihapus termasuk pesan pada inbox user lain"
                + "\nApakaah Anda yakin?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (i==JOptionPane.YES_OPTION){
            koneksi.delete("Pesan", "Pengirim", CurentUser);
            isiKotakKeluar();
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JDialog DaftarForm;
    private javax.swing.JDialog LoginForm;
    private javax.swing.JDialog SendForm;
    private javax.swing.JTable TBKeluar;
    private javax.swing.JTable TBMasuk;
    private javax.swing.JTabbedPane TabPane;
    private javax.swing.JLabel Userini;
    private javax.swing.JTextField daftar_nama;
    private javax.swing.JTextField daftar_pass;
    private javax.swing.JTextArea isi1;
    private javax.swing.JTextArea isi2;
    private javax.swing.JTextArea isitext;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPasswordField password;
    private javax.swing.JComboBox<String> target;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
